- name: Setup Tomcat 9 on Ubuntu
  hosts: appsrvgrp
  become: yes

  tasks:
    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Add tomcat group
      group:
        name: tomcat

    - name: Add tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        create_home: no

    - name: Create tomcat directory
      file:
        path: /usr/local/tomcat9
        state: directory
        owner: tomcat
        group: tomcat
        mode: '0755'

    - name: Download Tomcat 9.0.106
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.106/bin/apache-tomcat-9.0.106.tar.gz
        dest: /tmp/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /usr/local/tomcat9
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Set ownership
      file:
        path: /usr/local/tomcat9
        state: directory
        recurse: yes
        owner: tomcat
        group: tomcat

    - name: Copy Tomcat systemd service file
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat 9 Web Application Container
          After=network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          Environment=CATALINA_PID=/usr/local/tomcat9/temp/tomcat.pid
          Environment=CATALINA_HOME=/usr/local/tomcat9
          Environment=CATALINA_BASE=/usr/local/tomcat9
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          ExecStart=/usr/local/tomcat9/bin/startup.sh
          ExecStop=/usr/local/tomcat9/bin/shutdown.sh
          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd
        - Start and enable tomcat

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec

    - name: Start and enable tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started
