- name: Setup Tomcat9 & Deploy Artifact
  hosts: appsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"

  tasks:
    - name: Download latest VProfile.war from Nexus
      get_url:
        url: "http://172.31.94.127:8081/repository/vprofile-release/QA/25-06-19_084637/7/25-06-19_084637-7.war"
        dest: "/tmp/vproapp-25-06-19_084637-7.war"
      register: wardeploy
      tags:
        - deploy

    - stat:
        path: /usr/local/tomcat9/webapps/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Stop tomcat service
      service:
        name: tomcat
        state: stopped
      tags:
        - deploy

    - name: Archive ROOT dir with timestamp
      archive:
        path: /usr/local/tomcat9/webapps/ROOT
        dest: "/opt/ROOT_{{timestamp}}.tgz"
      when: artifact_stat.stat.exists
      register: archive_info
      tags:
        - deploy

    - name: Copy ROOT dir with old_ROOT name
      shell: cp -r ROOT old_ROOT
      args:
        chdir: /usr/local/tomcat9/webapps/
      tags:
        - deploy

    - name: Delete current artifact
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/local/tomcat9/webapps/ROOT
        - /usr/local/tomcat9/webapps/ROOT.war
      when: archive_info.changed
      tags:
        - deploy

    - name: Try deploy artifact else restore from previous old_ROOT
      block:
        - name: Deploy vprofile artifact
          copy:
            src: "/tmp/vproapp-25-06-19_084637-7.war"
            dest: /usr/local/tomcat9/webapps/ROOT.war
            remote_src: yes
          register: depl
