---
- name: Deploy vprofile WAR to Tomcat
  hosts: appsrvgrp
  become: yes

  vars:
    dest_dir: /usr/local/tomcat8/webapps
    war_temp_path: "/tmp/vproapp-{{ vprofile_version }}"

  tasks:
    - name: Download latest WAR from Nexus
      get_url:
        url: "http://{{ nexusip }}:8081/repository/{{ reponame }}/{{ groupid }}/{{ time }}/{{ build }}/{{ vprofile_version }}"
        dest: "{{ war_temp_path }}"
        mode: '0644'
        url_username: "{{ USER }}"
        url_password: "{{ PASS }}"
        force: yes

    - name: Stop tomcat service
      systemd:
        name: tomcat
        state: stopped

    - name: Backup existing ROOT folder
      shell: |
        if [ -d {{ dest_dir }}/ROOT ]; then
          timestamp=$(date +%Y%m%d%H%M%S)
          mv {{ dest_dir }}/ROOT {{ dest_dir }}/ROOT_$timestamp
        fi

    - name: Remove old ROOT.war
      file:
        path: "{{ dest_dir }}/ROOT.war"
        state: absent

    - name: Deploy new WAR
      copy:
        src: "{{ war_temp_path }}"
        dest: "{{ dest_dir }}/ROOT.war"
        remote_src: yes
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Start tomcat service
      systemd:
        name: tomcat
        state: started

    - name: Wait until ROOT.war is extracted
      wait_for:
        path: "{{ dest_dir }}/ROOT"
        state: directory
        timeout: 300
